version: '3.8'

services:
  graph-api:
    build: .
    container_name: graph-api-container
    volumes:
      - ./app:/app
    env_file:
      - .env  # Añadir esta línea
    command: python /app/GraphApi.py
